version: '3.7'
networks:
  kong-net:
    external: false

services:
  gatewayservice:
    image: gatewayservice
    build:
      context: .
      dockerfile: ./packages/OcelotGateway/Dockerfile
    ports:
      - "8082:8080"
    networks:
      - kong-net

  productdb:
    image: 'mongo:latest'
    container_name: product_mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - kong-net

  categorydb:
    image: 'mongo:latest'
    container_name: category_mongodb
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - categorydb_data:/data/db
    networks:
      - kong-net

  productservice:
    image: productservice:latest
    deploy:
      replicas: 3
    networks:
      - kong-net

  productservice2:
    image: productservice:latest
    deploy:
      replicas: 3
    networks:
      - kong-net

  orderservice:
    image: orderservice:latest
    deploy:
      replicas: 3
    networks:
      - kong-net

  orderservice2:
    image: orderservice:latest
    deploy:
      replicas: 3
    networks:
      - kong-net

  categoryservice:
    image: categoryservice
    deploy:
      replicas: 3
    networks:
      - kong-net

  categoryservice2:
    image: categoryservice
    deploy:
      replicas: 3
    networks:
      - kong-net

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    restart: unless-stopped
    networks:
      - kong-net

  seq:
    image: datalust/seq:latest
    ports:
      - "5342:80"
      - "5341:5341"
    volumes:
      - seq_data:/data
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - kong-net

  vault:
    image: hashicorp/vault
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp": {"address": "0.0.0.0:8200","tls_disable": "1"}}],"ui": true,"storage": {"file": {"path": "/vault/data"}},"rate_limit": {"default": {"rate": 500,"burst": 1000},"path_rate_limiter": {"/v1/secret/data/*": {"rate": 1000,"burst": 2000}},"/v1/sys/*": {"rate": 100,"burst": 200}}},"audit": {"file": {"file_path": "/vault/logs/audit.log"}}}'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    command: sh -c "chown -R 100:100 /vault/data && vault server -config=/vault/config/local.json"
    networks:
      - kong-net

  orderdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecret7!
      POSTGRES_DB: Order_db
    ports:
      - "5433:5432"
    volumes:
      - orderdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net

  userdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net

  userservice:
    image: userservice
    deploy:
      replicas: 3
    networks:
      - kong-net

  userservice2:
    image: userservice
    deploy:
      replicas: 3
    networks:
      - kong-net

  redis:
    image: 'redislabs/redisearch:latest'
    container_name: 'redis'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '6379:6379'
    networks:
      - kong-net

  authdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: Auth_db
    ports:
      - "5434:5432"
    volumes:
      - authdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net

  authservice:
    image: authservice
    deploy:
      replicas: 3
    networks:
      - kong-net

  authservice2:
    image: authservice
    deploy:
      replicas: 3
    networks:
      - kong-net

  kong-database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "5435:5435"
    volumes:
      - kong-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net

  kong-migrations:
    image: kong/kong-gateway:3.7.0.0
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PASSWORD: test
      KONG_PG_PASSWORD: kongpass
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong:
    image: kong/kong-gateway:3.7.0.0
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8007
    ports:
      - "8005:8000"
      - "8449:8443"
      - "8006:8001"
      - "8451:8444"
      - "8007:8002"
      - "8001:8001"
    depends_on:
      - kong-database
    restart: on-failure
    networks:
      - kong-net

  kongsetup:
    image: examproject-kongsetup:latest
    build:
      context: .
      dockerfile: ./packages/KongConfiguration/Dockerfile
    restart: "no"
    networks:
      - kong-net

volumes:
  mongodb_data: {}
  categorydb_data: {}
  seq_data: {}
  postgres-data: {}
  orderdb_data: {}
  vault_data: {}
  vault_logs: {}
  authdb_data: {}
  kong-data: {}
