version: '3.8'

services:
  productdb:
    image: 'mongo:latest'
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  categorydb:
    image: 'mongo:latest'
    container_name: mongodb
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - categorydb_data:/data/db

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ./projects/Product/ProductService/Dockerfile
    ports:
      - "8080:8080"
      - "8443:443"
    depends_on:
      - productdb

  categoryservice:
    image: categoryservice
    build:
      context: .
      dockerfile: ./projects/Category/CategoryService/Dockerfile
    ports:
      - "8090:8080"
      - "8444:443"
    depends_on:
      - categorydb

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    ports:
      - "5342:80"
      - "5341:5341"
    volumes:
      - seq_data:/data
    environment:
      ACCEPT_EULA: "Y"

volumes:
  mongodb_data:
  categorydb_data:
  seq_data: